Repository otakedev/ceihm-groupe-7, pull requests merged in 2021-02, with the labels that each got.

#78 Feature/us 31
  lib/main.dart
  lib/mocks/products_mock.dart
  lib/screens/product_page/components/product_compatibility.dart
  lib/screens/product_page/components/product_details.dart
  lib/screens/product_page/components/product_origin.dart
  lib/screens/product_page/components/similar_products.dart
  lib/screens/product_page/product_page.dart
  lib/screens/similar_product_page/similar_product_page.dart
  lib/theme/colors.dart
Labels: US, task

#76 [#64] add snackbar to notify the user the profile is saved after updated
  lib/core/router.dart
  lib/screens/home_page.dart
  lib/screens/profile_pages/update_profile_page.dart
Labels: enhancement

#75 [#62] add popup menu to modify the profile regarding an ingredient
  lib/providers/profile_selector_provider.dart
  lib/screens/product_page/components/product_compatibility.dart
  lib/screens/product_page/components/product_details.dart
  lib/screens/product_page/components/product_ingredients.dart
  lib/screens/product_page/components/product_profile_menu.dart
  lib/screens/product_page/components/similar_products.dart
  lib/screens/product_page/product_page.dart
  lib/screens/similar_product_page/similar_product_page.dart
Labels: enhancement

#86 [#82] fix search bar result to fit the page
  lib/screens/home_page.dart
  lib/screens/product_page/components/similar_products.dart
  lib/screens/profile_pages/components/profile_tab_page.dart
  lib/screens/profile_pages/update_profile_page.dart
Labels: bug

#87 Fixed font size of similar products page and changed label of "Suivant" page
  lib/screens/profile_pages/profile_page.dart
  lib/screens/similar_product_page/similar_product_page.dart
Labels: bug
